name = "auto-crawl-tiktok-post-fb"
main = "index.ts"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[vars]
ENVIRONMENT = "development"

[env.production]
  [env.production.vars]
  ENVIRONMENT = "production"